# https://rust-lang.github.io/rustup/overrides.html#the-toolchain-file

[toolchain]
channel = "1.79" # https://doc.rust-lang.org/std/num/struct.NonZero.html
profile = "minimal"
components = ["rust-analyzer"]
