name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  windows:
    name: Windows 2019 Server
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
    - name: Info
      run: |
        rustc -V
        cargo -V
        cmd /C ver
    - name: Test (MSRV)
      run: cargo test
    - name: Test (Stable)
      run: cargo +stable test
  linux:
    name: Ubuntu Latest
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Info
      run: |
        rustc -V
        cargo -V
    - name: Test (MSRV)
      run: cargo test
    - name: Test (Stable)
      run: cargo +stable test
